# Builds the entire project and runs all unit tests as well as the integration test for the web platform.
name: Build verifier

on: [push]

jobs:
  build:  
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '10', '11', '12', '13', '14', '15', '16', '17' ]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: zulu
        java-version: ${{ matrix.java }}
        architecture: x64
    - name: Maven build
      run: chmod +x ./scripts/build-verifier.sh && ./scripts/build-verifier.sh
